### ISSUE TITLE
Design Checklist for Feb

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#469]
My list:

- [x] #447 
- [ ] /request rethink & general thoughts on request workflow
- [ ] Gifs? 
- [x] link resolver idea
- [x] update of mockups?? https://github.com/OAButton/discussion/blob/master/UX%20Mockups/Library/Bookmarklet/Library%20Bookmarklet%20V2%20Clarifications.md
- [ ] small changes to pages to make them look niceer e.g @chealsye request to make the page look nicer

Happy for other ideas.
