### ISSUE TITLE
Design Checklist for Feb 23rd

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/discussion#519]
- [x] small changes to pages to make them look niceer e.g @chealsye request to make the page look nicer
- [ ] /request rethink & general thoughts on request workflow
- [ ] Gifs
  - [ ] bookmarklet install for #507 
  - [ ] Gif for using the button on chrome / & making a request
  - [ ] Gif for using the browser button / & making a request
- [x] general thoughts on /account
- [x] discussion on social machines
- [ ] discussion on group accounts

**Comment by JosephMcArthur** [comment]
@OAButton/team anyone got anything they'd like us to spend some design time on?
